In [61]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [62]:
# loading the dataset
data = pd.read_csv(r'C:\Users\trigg\Documents\Otobong\vsc\Amdari\Fraudulent-Transaction-Detection-NovaPay\Data\nova_pay_combined.csv')

In [63]:
data.head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,exchange_rate_src_to_dest,device_id,new_device,ip_address,ip_country,location_mismatch,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,ATM,278.19,278.19,4.25,1.351351,9f292dcc-3297-4947-a260-6a1ef69041ff,False,221.78.171.180,US,False,0.123,standard,263,0.522,0,0.223,0,0,0.0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,12.758621,3a95b9f5-309f-4684-a46d-e2ff2435bf78,True,120.12.20.29,CA,False,0.569,standard,947,0.475,0,0.268,0,1,0.0,0
2,fc855034-3ea5-4993-9afa-b511d93fe5e8,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-03 23:02:43.468549+00:00,US,USD,CNY,mobile,160.33,160.33,2.70,7.142857,a4737752-9aac-43ed-9d8b-2ccdffc24052,False,223.96.181.93,US,False,0.437,enhanced,367,0.939,0,0.176,0,0,0.0,0
3,2cf8c08e-42ec-444d-a755-34b9a2a0a4ca,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-04 01:08:53.468549+00:00,US,USD,EUR,mobile,59.41,59.41,2.22,0.925926,6aeb85a3-5603-4221-896c-9e6882764f1a,False,186.228.15.74,US,False,0.594,standard,147,0.551,0,0.391,0,0,0.0,0
4,d907a74d-b426-438d-97eb-dbe911aca91c,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-10-04 09:35:03.468549+00:00,US,USD,INR,mobile,200.96,200.96,3.61,83.333333,a5b9250e-dbe0-4c5f-a6e7-5492b7349402,False,11.82.47.62,US,False,0.121,enhanced,257,0.894,0,0.257,0,0,0.0,0

In [64]:
# Counting unique values
data['is_fraud'].value_counts()

is_fraud
0    10403
1      997
Name: count, dtype: int64

In [65]:
pd.reset_option('display.max_rows')
# data.info()

In [66]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             11400 non-null  str
 1   customer_id                11400 non-null  str
 2   timestamp                  11371 non-null  str
 3   home_country               11400 non-null  str
 4   source_currency            11400 non-null  str
 5   dest_currency              11400 non-null  str
 6   channel                    11400 non-null  str
 7   amount_src                 11400 non-null  str
 8   amount_usd                 11095 non-null  float64
 9   fee                        11105 non-null  float64
 10  exchange_rate_src_to_dest  11400 non-null  float64
 11  device_id                  11400 non-null  str
 12  new_device                 11400 non-null  bool
 13  ip_address                 11095 non-null  str
 14  ip_country                 11099 non-null  str
 15  location_mismatch          11400 non-null  bool
 16  ip_risk_score              11400 non-null  float64
 17  kyc_tier                   11100 non-null  str
 18  account_age_days           11400 non-null  int64
 19  device_trust_score         11105 non-null  float64
 20  chargeback_history_count   11400 non-null  int64
 21  risk_score_internal        11400 non-null  float64
 22  txn_velocity_1h            11400 non-null  int64
 23  txn_velocity_24h           11400 non-null  int64
 24  corridor_risk              11400 non-null  float64
 25  is_fraud                   11400 non-null  int64
dtypes: bool(2), float64(7), int64(5), str(12)
memory usage: 2.1 MB

In [67]:
data['timestamp']

0        2022-10-03 18:40:59.468549+00:00
1        2022-10-03 20:39:38.468549+00:00
2        2022-10-03 23:02:43.468549+00:00
3        2022-10-04 01:08:53.468549+00:00
4        2022-10-04 09:35:03.468549+00:00
                       ...
11395    2025-11-25 10:05:35.573611+00:00
11396    2025-11-26 07:09:56.573611+00:00
11397    2025-11-27 06:19:11.573611+00:00
11398    2025-11-28 00:53:28.573611+00:00
11399    2025-11-29 20:10:47.573611+00:00
Name: timestamp, Length: 11400, dtype: str

In [68]:
data.isnull().mean()

transaction_id               0.000000
customer_id                  0.000000
timestamp                    0.002544
home_country                 0.000000
source_currency              0.000000
dest_currency                0.000000
channel                      0.000000
amount_src                   0.000000
amount_usd                   0.026754
fee                          0.025877
exchange_rate_src_to_dest    0.000000
device_id                    0.000000
new_device                   0.000000
ip_address                   0.026754
ip_country                   0.026404
location_mismatch            0.000000
ip_risk_score                0.000000
kyc_tier                     0.026316
account_age_days             0.000000
device_trust_score           0.025877
chargeback_history_count     0.000000
risk_score_internal          0.000000
txn_velocity_1h              0.000000
txn_velocity_24h             0.000000
corridor_risk                0.000000
is_fraud                     0.000000
dtype: float64

# Convert timestamp to datetime data type
# Convert amount_src to numeric data type
# Dropping identifiers
# Deal with duplicates
# Deal wth null values

data.isnull().mean()>0

In [69]:
data.isnull().mean()*100>0

transaction_id               False
customer_id                  False
timestamp                     True
home_country                 False
source_currency              False
dest_currency                False
channel                      False
amount_src                   False
amount_usd                    True
fee                           True
exchange_rate_src_to_dest    False
device_id                    False
new_device                   False
ip_address                    True
ip_country                    True
location_mismatch            False
ip_risk_score                False
kyc_tier                      True
account_age_days             False
device_trust_score            True
chargeback_history_count     False
risk_score_internal          False
txn_velocity_1h              False
txn_velocity_24h             False
corridor_risk                False
is_fraud                     False
dtype: bool

In [70]:
non_missing_cols = data.columns[data.isnull().mean()*100 > 0]

In [71]:
data_non_missing = data[non_missing_cols]

In [72]:
data_non_missing.head()

,timestamp,amount_usd,fee,ip_address,ip_country,kyc_tier,device_trust_score
0,2022-10-03 18:40:59.468549+00:00,278.19,4.25,221.78.171.180,US,standard,0.522
1,2022-10-03 20:39:38.468549+00:00,154.29,4.24,120.12.20.29,CA,standard,0.475
2,2022-10-03 23:02:43.468549+00:00,160.33,2.70,223.96.181.93,US,enhanced,0.939
3,2022-10-04 01:08:53.468549+00:00,59.41,2.22,186.228.15.74,US,standard,0.551
4,2022-10-04 09:35:03.468549+00:00,200.96,3.61,11.82.47.62,US,enhanced,0.894

In [73]:
data.describe(include = ['str', 'bool'])

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,device_id,new_device,ip_address,ip_country,location_mismatch,kyc_tier
count,11400,11400,11371,11400,11400,11400,11400,11400,11400,11400,11095,11099,11400,11100
unique,11200,1315,11141,7,3,9,12,9856,2113,2,10900,9,2,14
top,4662cb2d-21b2-4390-ba38-5a1eddebdc7c,402cccc9-28de-45b3-9af7-cc5302aa1f93,0000-00-00T00:00:00Z,US,USD,NGN,mobile,100.0,e70db499-19e1-4927-b04f-3ebfcf62e33c,False,194.179.17.152,US,False,standard
freq,2,1510,21,7940,8031,1474,6366,15,87,10047,2,6848,9548,7931

In [74]:
data.describe()

,amount_usd,fee,exchange_rate_src_to_dest,ip_risk_score,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
count,11095.000000,11105.000000,11400.000000,11400.000000,11400.000000,11105.000000,11400.000000,11400.000000,11400.000000,11400.000000,11400.000000,11400.000000
mean,452.022083,100.309441,167.540397,0.396726,393.793158,0.653681,0.048509,0.267134,0.458333,0.723509,0.045501,0.087456
std,1403.973062,958.128504,382.023827,0.270507,342.348393,0.273012,0.256194,0.142983,1.524494,1.958390,0.084942,0.282515
min,7.230000,-1.000000,0.592000,0.004000,1.000000,-0.100000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,92.465000,2.380000,1.000000,0.209000,147.000000,0.515000,0.000000,0.169000,0.000000,0.000000,0.000000,0.000000
50%,163.480000,3.500000,7.142857,0.325000,298.000000,0.658000,0.000000,0.223000,0.000000,0.000000,0.000000,0.000000
75%,302.190000,5.550000,73.529412,0.487000,661.000000,0.894000,0.000000,0.391000,0.000000,0.000000,0.050000,0.000000
max,12498.570000,9999.990000,1388.888889,1.200000,1095.000000,0.999000,2.000000,0.900000,8.000000,11.000000,0.250000,1.000000

In [75]:
data.duplicated().sum()

np.int64(200)

In [76]:
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce')
data['amount_src'] = pd.to_numeric(data['amount_src'], errors='coerce')

In [77]:
data[['amount_src', 'timestamp']].dtypes

amount_src                float64
timestamp     datetime64[us, UTC]
dtype: object

In [78]:
data['fee'].dtype

dtype('float64')

In [79]:
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)
for col in data.select_dtypes(include=['str', 'bool']).columns.tolist():
    print(data[col].value_counts())
    print('------------------')

transaction_id
4662cb2d-21b2-4390-ba38-5a1eddebdc7c    2
e69d481f-2ee3-4621-a58a-73fec8c63eca    2
8537371a-7eae-4108-89c9-5660e5025a88    2
2e553c23-063e-4b5e-aa2e-8a41d6aa61ca    2
a9198fb0-d831-48df-b434-c30a39078aa3    2
                                       ..
b5ef3323-46d2-4f6c-9c19-43df4e55df48    1
54f00f78-94aa-4a08-bf6b-12877aa47186    1
6a51f0e8-f5d1-4fe6-91a0-655fccd79fa5    1
4aad7389-2b62-4885-a23e-aa3ecd5cfaf9    1
fdffeb16-192a-4483-9b1e-9928e23269c2    1
Name: count, Length: 11200, dtype: int64
------------------
customer_id
402cccc9-28de-45b3-9af7-cc5302aa1f93    1510
d71c91b4-fee8-4104-9856-a5c6109a62e3    1355
7041b9c1-3719-4ca8-9a6b-811b47cea6c0    1345
6d0d9b27-fa26-45f8-93b1-2df29d182d9c    1066
af8ca4c4-8703-4c55-b66c-2b76cd70040d     915
                                        ...
8734e6a7-f34e-49f2-b559-1d62a756664c       1
c18070a6-bdb9-4df3-9df7-5d92c0bff424       1
2003e2a1-f3b1-4e2e-8d0e-488cfacf68ca       1
8b1cf558-4ed7-48ee-b330-75db6efd4840       1
b69010dc-ab0a-4fd2-a79e-65e4c6efbcd9       1
Name: count, Length: 1315, dtype: int64
------------------
home_country
US         7940
UK         2119
CA         1221
 US          68
unknown      32
 UK          13
 CA           7
Name: count, dtype: int64
------------------
source_currency
USD    8031
GBP    2139
CAD    1230
Name: count, dtype: int64
------------------
dest_currency
NGN    1474
USD    1328
INR    1325
CNY    1324
PHP    1314
GBP    1296
CAD    1282
EUR    1196
MXN     861
Name: count, dtype: int64
------------------
channel
mobile       6366
web          3727
ATM          1008
mobille        60
 mobile        48
MOBILE         47
unknown        37
WEB            36
 web           34
weeb           24
ATm             9
 ATM            4
Name: count, dtype: int64
------------------
device_id
e70db499-19e1-4927-b04f-3ebfcf62e33c    87
9957de24-ace9-4938-bb81-6e7e41276961    75
917faeeb-252b-4379-8ba3-8c4bae9791fb    74
1d8d6841-8816-4c1a-9c03-cda94a9516ae    74
9849347e-5774-4f24-ac70-de0c98536adf    73
                                        ..
5c06f00d-a089-402b-9b14-e7bc7ae56ed2     1
dafd943c-f12f-48b9-83df-401efaad0fe3     1
94475656-37f3-4b9c-b3cd-6d89416866ac     1
0eab90ef-4273-4239-8b51-2c96b2a24756     1
1bf43786-477e-468a-9f82-4b4eeca13f61     1
Name: count, Length: 2113, dtype: int64
------------------
new_device
False    10047
True      1353
Name: count, dtype: int64
------------------
ip_address
194.179.17.152     2
165.110.247.200    2
24.73.140.66       2
240.36.95.84       2
5.134.140.197      2
                  ..
221.126.239.197    1
26.6.123.44        1
184.150.56.237     1
31.125.175.93      1
216.205.157.160    1
Name: count, Length: 10900, dtype: int64
------------------
ip_country
US         6848
UK         2407
CA         1726
 US          49
unknown      33
 UK          18
 CA          15
NAN           2
 nan          1
Name: count, dtype: int64
------------------
location_mismatch
False    9548
True     1852
Name: count, dtype: int64
------------------
kyc_tier
standard       7931
enhanced       1829
low            1039
standrd          72
STANDARD         70
 standard        65
unknown          32
 enhanced        17
ENHANCED         17
enhancd          12
 low              8
LOW               5
 nan              2
NAN               1
Name: count, dtype: int64
------------------

# Cleaning ip_country column

In [80]:

# # Remove leading/trailing spaces
# data['ip_country'] = data['ip_country'].str.strip()

# # Convert everything to uppercase
# data['ip_country'] = data['ip_country'].str.upper()

# # Replace invalid values with actual NaN
# data['ip_country'] = data['ip_country'].replace(
#     ['UNKNOWN', 'NAN', 'NONE', 'NULL', ''],
#     np.nan
# )

# Cleaning kyc_tier column

In [81]:
# # Remove leading/trailing spaces
# data['kyc_tier'] = data['kyc_tier'].str.strip()

# # Convert to lowercase
# data['kyc_tier'] = data['kyc_tier'].str.lower()

# # Fix spelling mistakes and inconsistencies
# data['kyc_tier'] = data['kyc_tier'].replace({
#     'standrd': 'standard',
#     'enhancd': 'enhanced'
# })

# # Replace invalid values with NaN
# data['kyc_tier'] = data['kyc_tier'].replace(
#     ['unknown', 'nan', 'none', 'null', ''],
#     np.nan
# )

In [82]:
# data.head()

In [83]:
for col in data.select_dtypes(include=['str', 'bool']).columns.tolist():
    print(data[col].value_counts())
    print('------------------')

transaction_id
4662cb2d-21b2-4390-ba38-5a1eddebdc7c    2
e69d481f-2ee3-4621-a58a-73fec8c63eca    2
8537371a-7eae-4108-89c9-5660e5025a88    2
2e553c23-063e-4b5e-aa2e-8a41d6aa61ca    2
a9198fb0-d831-48df-b434-c30a39078aa3    2
                                       ..
b5ef3323-46d2-4f6c-9c19-43df4e55df48    1
54f00f78-94aa-4a08-bf6b-12877aa47186    1
6a51f0e8-f5d1-4fe6-91a0-655fccd79fa5    1
4aad7389-2b62-4885-a23e-aa3ecd5cfaf9    1
fdffeb16-192a-4483-9b1e-9928e23269c2    1
Name: count, Length: 11200, dtype: int64
------------------
customer_id
402cccc9-28de-45b3-9af7-cc5302aa1f93    1510
d71c91b4-fee8-4104-9856-a5c6109a62e3    1355
7041b9c1-3719-4ca8-9a6b-811b47cea6c0    1345
6d0d9b27-fa26-45f8-93b1-2df29d182d9c    1066
af8ca4c4-8703-4c55-b66c-2b76cd70040d     915
                                        ...
8734e6a7-f34e-49f2-b559-1d62a756664c       1
c18070a6-bdb9-4df3-9df7-5d92c0bff424       1
2003e2a1-f3b1-4e2e-8d0e-488cfacf68ca       1
8b1cf558-4ed7-48ee-b330-75db6efd4840       1
b69010dc-ab0a-4fd2-a79e-65e4c6efbcd9       1
Name: count, Length: 1315, dtype: int64
------------------
home_country
US         7940
UK         2119
CA         1221
 US          68
unknown      32
 UK          13
 CA           7
Name: count, dtype: int64
------------------
source_currency
USD    8031
GBP    2139
CAD    1230
Name: count, dtype: int64
------------------
dest_currency
NGN    1474
USD    1328
INR    1325
CNY    1324
PHP    1314
GBP    1296
CAD    1282
EUR    1196
MXN     861
Name: count, dtype: int64
------------------
channel
mobile       6366
web          3727
ATM          1008
mobille        60
 mobile        48
MOBILE         47
unknown        37
WEB            36
 web           34
weeb           24
ATm             9
 ATM            4
Name: count, dtype: int64
------------------
device_id
e70db499-19e1-4927-b04f-3ebfcf62e33c    87
9957de24-ace9-4938-bb81-6e7e41276961    75
917faeeb-252b-4379-8ba3-8c4bae9791fb    74
1d8d6841-8816-4c1a-9c03-cda94a9516ae    74
9849347e-5774-4f24-ac70-de0c98536adf    73
                                        ..
5c06f00d-a089-402b-9b14-e7bc7ae56ed2     1
dafd943c-f12f-48b9-83df-401efaad0fe3     1
94475656-37f3-4b9c-b3cd-6d89416866ac     1
0eab90ef-4273-4239-8b51-2c96b2a24756     1
1bf43786-477e-468a-9f82-4b4eeca13f61     1
Name: count, Length: 2113, dtype: int64
------------------
new_device
False    10047
True      1353
Name: count, dtype: int64
------------------
ip_address
194.179.17.152     2
165.110.247.200    2
24.73.140.66       2
240.36.95.84       2
5.134.140.197      2
                  ..
221.126.239.197    1
26.6.123.44        1
184.150.56.237     1
31.125.175.93      1
216.205.157.160    1
Name: count, Length: 10900, dtype: int64
------------------
ip_country
US         6848
UK         2407
CA         1726
 US          49
unknown      33
 UK          18
 CA          15
NAN           2
 nan          1
Name: count, dtype: int64
------------------
location_mismatch
False    9548
True     1852
Name: count, dtype: int64
------------------
kyc_tier
standard       7931
enhanced       1829
low            1039
standrd          72
STANDARD         70
 standard        65
unknown          32
 enhanced        17
ENHANCED         17
enhancd          12
 low              8
LOW               5
 nan              2
NAN               1
Name: count, dtype: int64
------------------

Dealing with duplicates

In [84]:
data.drop_duplicates(subset=['transaction_id', 'customer_id', 'device_id'], inplace=True)

In [85]:
data.duplicated().sum()

np.int64(0)

Drop Identifiers

In [86]:
data.drop(columns=['transaction_id', 'customer_id', 'device_id'], inplace=True)

Dealing with inconsistent categorical variable.

In [90]:
for col in data.select_dtypes(include=['object']).columns.tolist():
    data[col] = data[col].str.strip().str.lower()
    print(data[col].value_counts())
    print('------------------')

home_country
us         7852
uk         2104
ca         1212
unknown      32
Name: count, dtype: int64
------------------
source_currency
usd    7875
gbp    2111
cad    1214
Name: count, dtype: int64
------------------
dest_currency
ngn    1447
inr    1304
usd    1302
cny    1297
php    1290
gbp    1273
cad    1260
eur    1177
mxn     850
Name: count, dtype: int64
------------------
channel
mobile     6336
web        3742
atm        1002
mobille      59
unknown      37
weeb         24
Name: count, dtype: int64
------------------
ip_address
221.78.171.180     1
120.12.20.29       1
223.96.181.93      1
186.228.15.74      1
11.82.47.62        1
                  ..
221.126.239.197    1
26.6.123.44        1
184.150.56.237     1
31.125.175.93      1
216.205.157.160    1
Name: count, Length: 10900, dtype: int64
------------------
ip_country
us         6761
uk         2390
ca         1718
unknown      32
nan           3
Name: count, dtype: int64
------------------
kyc_tier
standard    7913
enhanced    1827
low         1047
standrd       72
unknown       31
enhancd       12
nan            3
Name: count, dtype: int64
------------------

C:\Users\trigg\AppData\Local\Temp\ipykernel_45396\1676845481.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in data.select_dtypes(include=['object']).columns.tolist():

Dealing with null values

Calculate  echange rate per currency